LANGUAGES = {
    "en": {
        "welcome": "Rent-A-Car",
        "search_placeholder": "Search cars...",
        "logout": "Logout",
        "login": "Login",
        "register": "Register",
        "office_map": "Office Map",
        "no_cars_found": "No cars found matching your criteria.",
        "results": "Results",
        "show_cars": "Show Cars",
        "back_to_home": "Back to Home",
        "password": "Password",
        "login": "Login",
        "email": "E-mail",
        "location": "Location",
        "address": "Address",
        "phone": "Phone",
        "transmission": "Transmission",
        "cost": "Cost",
        "deposit": "Deposit",
        "mileage": "Mileage",
        "age": "Age",
        "rental": "Rental Cost",
        "search": "Search",
        "username": "Username",
        "city": "City",
        "country": "Country",
        "login_success": "Welcome",
        "invalid_login": "Invalid email or password",
        "invalid_regis": "Email or Username already taken",
        "regis_success": "Registration successful! You can now log in",
        "logged_out": "You have been logged out",
        "pickup_office": "Pickup Office",
        "pickup_date": "Pickup Date",
        "pickup_time": "Pickup Time",
        "return_office": "Return Office",
        "return_date": "Return Date",
        "return_time": "Return Time",
        "rent_for_days": "Rent",
        "select_office": "Select Office",
        "select_return": "Select Return Office",
        "filters": "Filters",
        "automatic": "Automatic",
        "manual": "Manual",
        "lowhigh": "Low to High",
        "highlow": "High to Low",
        "applyf": "Apply Filters",
        "clearf": "Clear Filters",
        "sort": "Sort By",
        "buy_now": "Buy Now",
        "greet": "Welcome to our website",
        "photo": "Profile Photo",
        "geofail1": "Geolocation service failed, using default location",
        "geofail2": "Geolocation is not supported by this browser, using default location",
        "geofail3": "We could not access your location, using default location",
    },
    "tr": {
        "welcome": "Araba Kiralama",
        "search_placeholder": "Araba ara...",
        "logout": "Çıkış Yap",
        "login": "Giriş Yap",
        "register": "Kayıt Ol",
        "office_map": "Ofis Haritası",
        "no_cars_found": "Aradığınız kriterlere uygun araba bulunamadı.",
        "results": "Sonuçlar",
        "show_cars": "Arabaları Göster",
        "back_to_home": "Ana Sayfaya Dön",
        "password": "Şifre",
        "login": "Giriş Yap",
        "email": "E-posta",
        "location": "Konum",
        "address": "Adres",
        "phone": "Telefon",
        "transmission": "Vites",
        "cost": "Fiyat",
        "deposit": "Depozito",
        "mileage": "Kilometre",
        "age": "Yaş",
        "rental": "Kiralama Bedeli",
        "search": "Ara",
        "username": "Kullanıcı Adı",
        "city": "Şehir",
        "country": "Ülke",
        "login_success": "Hoşgeldin",
        "invalid_login": "Geçersiz e-posta veya şifre",
        "invalid_regis": "E-posta veya kullanıcı adı kullanımda",
        "regis_success": "Kayıt başarılı! Şimdi giriş yapabilirsin",
        "logged_out": "Çıkış yaptınız",
        "pickup_office": "Teslim Alma Ofisi",
        "pickup_date": "Teslim Alma Tarihi",
        "pickup_time": "Teslim Alma Saati",
        "return_office": "İade Ofisi",
        "return_date": "İade Tarihi",
        "return_time": "İade Saati",
        "rent_for_days": "Kirala",
        "select_office": "Ofis Seç",
        "select_return": "İade Ofisi Seç",
        "filters": "Filtreler",
        "automatic": "Otomatik",
        "manual": "Manuel",
        "lowhigh": "Düşükten Yükseğe",
        "highlow": "Yüksekten Düşüğe",
        "applyf": "Filtreleri Uygula",
        "clearf": "Filtreleri Temizle",
        "sort": "Sırala",
        "buy_now": "Hemen Öde",
        "greet": "Sitemize hoş geldiniz",
        "photo": "Profil Fotoğrafı",
        "geofail1": "Geolocation servisi başarısız oldu, varsayılan konum kullanılıyor",
        "geofail2": "Geolocation bu tarayıcıda desteklenmiyor, varsayılan konum kullanılıyor",
        "geofail3": "Konumunuza erişemedik, varsayılan konum kullanılıyor",
    },
}